### PR TITLE
Display flash message regarding to the returned API response

### PR DESCRIPTION
**Pull request by hkhattabii**
When an action is triggered from the UI to save components or connections, an error may occur.  Regarding to that error, the flash message should be tailored to be displayed in the UI.

When the users click on "save component", the web application send a POST to the API. If it is already exists, send a PUT, if not display an error message regarding to the message coming from the API. 

Do the same for the PUT, if there is an error, display the message.

### CODE REVIEW

**Comment by BerrevoetsRobbe** [comment]
edit connection

* mapping of connection parameters is not correct (e.g. host, tls, port...)
* mark environment dropdown with title 'environment'

**Comment by BerrevoetsRobbe** [comment]
edit component

* title of component dialog is not set
* the dropdown contains two times the same entry, why is this needed?

**Comment by BerrevoetsRobbe** [comment]
connection from openapi transformation

from connection entry:
* connection parameters not correctly mapped (host, port...)
* replace the '+' button with a save icon (diskette)

**Comment by BerrevoetsRobbe** [comment]
> edit connection
> 
> * mapping of connection parameters is not correct (e.g. host, tls, port...)
> * mark environment dropdown with title 'environment'
> * make the popup wider
> * replace 'validate' and 'cancel' buttons with something similar to the 'discard changes' and 'update action' buttons in the edit action popup

test

**Comment by hkhattabii** [comment]
> connection from openapi transformation
> 
> from connection entry:
> 
> * connection parameters not correctly mapped (host, port...)
> * replace the '+' button with a save icon (diskette)



> edit connection
> 
> * mapping of connection parameters is not correct (e.g. host, tls, port...)
> * mark environment dropdown with title 'environment'
> * make the popup wider
> * replace 'validate' and 'cancel' buttons with something similar to the 'discard changes' and 'update action' buttons in the edit action popup



> edit component
> 
> * title of component dialog is not set
> * the dropdown contains two times the same entry, why is this needed?

The title of component dialog issue have been fixed this morning. It is needed to choose which component has to be connected to a specific connection. I will add the environment to differenciate the connections

**Pull request closed without merging**
